version: ""
services:
    hosted_service_api:
        container_name:
        build:
            context:
            dockerfile: ./docker/Dockerfile
        image: hosted_service_api
        ports:
            - "8080:8080"
        environment:
            PORT: 8080